sudo: required

services:
        - docker

before_install:
        - docker build -t wari0/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true wari0/react-test npm test

after_success:
        - docker build -t wari0/multi-client:latest ./client
        - docker build -t wari0/multi-nginx:latest   ./nginx
        - docker build -t wari0/multi-server:latest  ./server
        - docker build -t wari0/multi-worker:latest  ./worker
        - docker logout
        - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" "https://registry-1.docker.io/v1/"
        - docker push wari0/multi-client:latest 
        - docker push wari0/multi-nginx:latest 
        - docker push wari0/multi-server:latest 
        - docker push wari0/multi-worker:latest 
