sudo: required

services:
        - docker

before_install:
        - docker build -t wari0/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true wari0/react-test npm test

after_success:
        - docker build -t wari0/multi-client ./client
        - docker build -t wari0/multi-nginx  ./nginx
        - docker build -t wari0/multi-server ./server
        - docker build -t wari0/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push wari0/k8s 
